### PR TITLE
Add network ingress dns section

### PR DESCRIPTION
**Pull request by candita**
@miciah @rfredette please take a look at this first draft.

OWNERS:
miciah
rfredette
candita
frobware

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
this looks like a great start, thanks Candace

i have one question, is there a reason to use the H3 ('###') and H4 ('####') headers? (i was expecting to see an H2 in there somewhere)

**Comment by candita** [comment]
> this looks like a great start, thanks Candace
> 
> i have one question, is there a reason to use the H3 ('###') and H4 ('####') headers? (i was expecting to see an H2 in there somewhere)

No, these can be replaced.  We can change in the next update.

**Comment by elmiko** [comment]
cool, thanks
/lgtm

**Comment by elmiko** [comment]
@candita i'd like to merge this today unless you would like to keep it open for a few more reviews?

**Pull request merged**
