### PR TITLE
add owners files

### PR DESCRIPTION
**Pull request by elmiko**
The files created here have been inspired by the people who have
contributed to the various docs.

### CODE REVIEW

**Comment by elmiko** [comment]
@patrickdillon @Miciah @candita @Prashanth684 @bostrt ptal as i have signed you up to be owners here =)

**Comment by Prashanth684** [comment]
lgtm for rhcos, i'm glad to be an approver/reviewer, but it would be good to get someone from rhcos team also to oversee future additions.

**Comment by elmiko** [comment]
@Prashanth684 do you have any suggestions on who i might reach out to?

**Comment by Prashanth684** [comment]
@elmiko maybe let's start with Micah Abbott ? (i couldn't tag him here)

**Comment by elmiko** [comment]
thanks @Prashanth684 , i'll reach out to Micah in slack

**Comment by elmiko** [comment]
updated to add more rhcos approvers

**Comment by elmiko** [comment]
updated to add more installer approvers

thanks everyone!

**Pull request merged**
