### PR TITLE
add text to enhancement index file

### PR DESCRIPTION
**Pull request by elmiko**
this adds the initial text plus some links to previous enhancements.

### CODE REVIEW

**Comment by lobziik** [comment]
Maybe it might make sense to briefly describe a set of topics which should be covered in enhancement?
Like possible topology diagram, DNS strategy, etc

**Comment by elmiko** [comment]
yeah, i can add some of that

**Comment by elmiko** [comment]
update
* added a section on writing the enhancement with some topical tips

**Comment by lobziik** [comment]
Cool! Thanks a lot!
/lgtm

**Pull request merged**
